# Generated by Django 2.2 on 2019-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_body', models.TextField()),
                ('article_img', models.ImageField(upload_to='static/media')),
                ('article_created', models.DateTimeField(verbose_name='date_published')),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
    ]
